MvcKutuphaneProjesi/Controllers/KitapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneProjesi.Models.Entity;

namespace MvcKutuphaneProjesi.Controllers
{
    public class KitapController : Controller
    {
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        // GET: Kitap
        public ActionResult Index()
        {
            var degerler = db.TBLKITAPs.ToList();
            return View(degerler);
        }
        [HttpGet]
        public ActionResult KitapEkle()
        {
            List<SelectListItem> deger1 = (from i in db.TBLKATEGORIs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = i.kategori_ad,
                                               Value = i.kategori_id.ToString()
                                           }).ToList();
            ViewBag.dgr1 = deger1;
            List<SelectListItem> deger2 = (from a in db.TBLYAZARs.ToList()
                                           select new SelectListItem
                                           {
                                               Text = a.yazar_ad,
                                               Value=a.yazar_id.ToString()
                                                
                                           }).ToList();
            ViewBag.dgr2=deger2;
            return View();
        }
        [HttpPost]
        public ActionResult KitapEkle(TBLKITAP k)
        {
            var ktg = db.TBLKATEGORIs.Where(x => x.kategori_id == k.TBLKATEGORI.kategori_id).FirstOrDefault();
            var yzr = db.TBLYAZARs.Where(x => x.yazar_id == k.TBLYAZAR.yazar_id).FirstOrDefault();
            k.TBLKATEGORI = ktg;
            k.TBLYAZAR = yzr;
            db.TBLKITAPs.Add(k);
            db.SaveChanges();
            return RedirectToAction("Index");
            
        }

        public ActionResult KitapSil(int id)
        {
            var silinecek_kitap = db.TBLKITAPs.Find(id);
            db.TBLKITAPs.Remove(silinecek_kitap);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult KitapGetir(int id)
        {
            var getirilecek_kitap = db.TBLKITAPs.Find(id);
            return View("KitapGetir", getirilecek_kitap);
        }
        public ActionResult KitapGuncelle(TBLKITAP k)
        {
            var kitap = db.TBLKITAPs.Find(k.kitap_id);
            kitap.kitap_ad = k.kitap_ad;
            kitap.BASIMYILI = k.BASIMYILI;
            kitap.kitap_sayfa = k.kitap_sayfa;
            kitap.kitap_durum = k.kitap_durum;
            kitap.kitap_yayınevi = k.kitap_yayınevi;
            var ktg = db.TBLKATEGORIs.Where(x => x.kategori_id == k.kategori_id).FirstOrDefault();
            var yzr = db.TBLYAZARs.Where(x => x.yazar_id == k.yazar_id).FirstOrDefault();
            kitap.kategori_id = ktg.kategori_id;
            kitap.yazar_id = yzr.yazar_id;
            db.SaveChanges();
            return RedirectToAction("Index");

        }
    }
}

MvcKutuphaneProjesi/Views/Kitap/Index.cshtml
@using MvcKutuphaneProjesi.Models.Entity
@model List<TBLKITAP>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}
<link href="~/Views/Kitap/StyleSheet1.css" rel="stylesheet" />
<h1>Kitap Sayfası</h1>
<div style="margin-top:20px;margin-bottom:20px">
    <input type="text" class="form-control" placeholder="Kitap adını giriniz..." />
</div>
<table class="table table-bordered">
    
    <tr>
        <th>KİTAP ID</th>
        <th>KİTAP AD</th>
        <th>KATEGORİ</th>
        <th>YAZAR</th>
        <th>BASIMYILI</th>
        <th>YAYINEVİ</th>
        <th>SAYFA SAYISI</th>
        <th>KİTAP DURUM</th>
        <th>KİTAP SİL</th>
        <th>KİTAP GÜNCELLE</th>
    </tr>
    

 
    @foreach (var k in Model)
    {
        <tr>
            <td>@k.kitap_id</td>
            <td>@k.kitap_ad</td>
            <td>@k.TBLKATEGORI.kategori_ad</td>
            <td>@k.TBLYAZAR.yazar_ad</td>
            <td>@k.BASIMYILI</td>
            <td>@k.kitap_yayınevi</td>
            <td>@k.kitap_sayfa</td>
            <td>@k.kitap_durum</td>
            <td><a href="/Kitap/KitapSil/@k.kitap_id" class="btn btn-danger">SİL</a></td>
            <td><a href="/Kitap/KitapGetir/@k.kitap_id" class="btn btn-success">GÜNCELLE</a></td>

        </tr>
    }
    
</table>
<a href="/Kitap/KitapEkle/" class="btn btn-warning">Yeni Kitap Ekle</a>

MvcKutuphaneProjesi/Views/Kitap/KitapEkle.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div style="margin-top:15px">
        <label>Kitap Adı</label>
        @Html.TextBoxFor(k => k.kitap_ad, new { @class = "form-control" })
    </div>

    <div style="margin-top:15px">
        <label>Kitap Kategori</label>
        @Html.DropDownListFor(k => k.TBLKATEGORI.kategori_id, (List<SelectListItem>)ViewBag.dgr1, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Kitap Yazarı</label>
        @Html.DropDownListFor(k => k.TBLYAZAR.yazar_id, (List<SelectListItem>)ViewBag.dgr2, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Basımyılı</label>
        @Html.TextBoxFor(k => k.BASIMYILI, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Yayınevi</label>
        @Html.TextBoxFor(k => k.kitap_yayınevi, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>Sayfa Sayısı</label>
        @Html.TextBoxFor(k => k.kitap_sayfa, new { @class = "form-control" })
    </div>
    <button style="margin-top:15px" class="btn btn-warning">Kitabı Ekle</button>
    <br />
    <input type="hidden" name="kitap_durum" value="True" />




</form>

MvcKutuphaneProjesi/Views/Kitap/KitapGetir.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLKITAP
@{
    ViewBag.Title = "KitapGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}




@using (Html.BeginForm("KitapGuncelle", "Kitap", FormMethod.Post))
{
    @Html.HiddenFor(k => k.kitap_id)
    @Html.HiddenFor(k => k.kategori_id)
    @Html.HiddenFor(k => k.yazar_id)
    <div style="margin-top:15px"></div>
    <label style="margin-bottom:15px;margin-top:15px">Kitap AD</label>
    @Html.TextBoxFor(k => k.kitap_ad, new { @class = "form-control" })

    <label style="margin-top:15px">Kategori</label>
    @Html.TextBoxFor(y => y.TBLKATEGORI.kategori_ad, new { @class = "form-control", @style = "disabled='disabled'" })

    <label style="margin-top:15px">Yazar</label>
    @Html.TextBoxFor(y => y.TBLYAZAR.yazar_ad, new { @class = "form-control" })

    <label style="margin-top:15px"> Basımyılı</label>
    @Html.TextBoxFor(y => y.BASIMYILI, new { @class = "form-control" })

    <label style="margin-top:15px"> Yayınevi</label>
    @Html.TextBoxFor(y => y.kitap_yayınevi, new { @class = "form-control" })

    <label style="margin-top:15px"> Sayfa Sayısı</label>
    @Html.TextBoxFor(y => y.kitap_sayfa, new { @class = "form-control" })

    <label style="margin-top:15px"> Kitap Durum</label>
    @Html.TextBoxFor(y => y.kitap_durum, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Kitap Bilgilerini Güncelle</button>
    <input type="hidden" name="kitap_durum" value="True" />

}