MvcKutuphaneProjesi/Controllers/OduncController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneProjesi.Models.Entity;

namespace MvcKutuphaneProjesi.Controllers
{
    public class OduncController : Controller
    {
        // GET: Odunc
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();
        public ActionResult Index()
        {
            var degerler = db.TBLHAREKETs.Where(x=>x.TBLKITAP.kitap_durum==false).ToList();

            return View(degerler);
        }
        [HttpGet]
        public ActionResult OduncVer()
        {
            return View();
        }
        [HttpPost]
        public ActionResult OduncVer(TBLHAREKET p)
        {
            db.TBLHAREKETs.Add(p);
            db.SaveChanges();
            return View();
        }

      
        
        public ActionResult Odunciade(int id)
        {
            var odn = db.TBLHAREKETs.Find(id);
            return View("Odunciade", odn);
        }

        public ActionResult OduncGuncelle(TBLHAREKET h)
        {
            var odn = db.TBLHAREKETs.Find(h.hareket_id);
            odn.hareket_uyeningetirdigitarih = h.hareket_uyeningetirdigitarih;
            odn.TBLKITAP.kitap_durum = true;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

MvcKutuphaneProjesi/Views/Odunc/Index.cshtml
@using MvcKutuphaneProjesi.Models.Entity
@model List<TBLHAREKET>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<div style="margin-top:20px;margin-bottom:20px">
    <input type="text" class="form-control" placeholder="Kitap adını giriniz..." />
</div>
<table class="table table-bordered">

    <tr>
        <th>ISLEM ID</th>
        <th>KİTAP AD</th>
        <th>UYE ADI</th>
        <th>PERSONEL</th>
        <th>ALIŞ TARİHİ</th>
        <th>İADE TARİHİ</th>
        <th>KİTAP DURUM</th>
       
    </tr>



    @foreach (var h in Model)
    {
        <tr>
            <td>@h.hareket_id</td>
            <td>@h.TBLKITAP.kitap_ad</td>
            <td>@h.TBLUYELER.uye_ad</td>
            <td>@h.TBLPERSONEL.personel_bilgi</td>
            <td>@h.hareket_alistarih</td>
            <td>@h.hareket_iadetarih</td>   
            <td>@h.TBLKITAP.kitap_durum</td>   
            <td><a href="/Odunc/Odunciade/@h.hareket_id" class="btn btn-danger">Kitap İade Al</a></td>

        </tr>
    }

</table>

MvcKutuphaneProjesi/Views/Odunc/OduncVer.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "OduncVer";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<form class="form-group" method="post">
    <div></div>
    <div style="margin-top:15px">
        <label> UYE ID</label>
        @Html.TextBoxFor(u => u.uye_id, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>KİTAP ID</label>
        @Html.TextBoxFor(k => k.kitap_id, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>PERSONEL ID</label>
        @Html.TextBoxFor(p => p.personel_id, new { @class = "form-control" })
    </div>
    <div style="margin-top:15px">
        <label>ALIŞ TARİHİ</label>
        <input type="text" name="hareket_alistarih" class="form-control" value="@DateTime.Now.ToShortDateString()" />
    </div>
    <div style="margin-top:15px">
        <label>İADE TARİHİ</label>
        <input type="text" name="hareket_iadetarih" class="form-control" value="@DateTime.Now.AddDays(7).ToShortDateString()   " />
    </div>
    <button style="margin-top:15px" class="btn btn-info">Ödünç Kitap Ver</button>

</form>

MvcKutuphaneProjesi/Views/Odunc/Odunciade.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLHAREKET
@{
    ViewBag.Title = "Odunciade";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("OduncGuncelle", "Odunc", FormMethod.Post))
{
    <div style="margin-top:15px"></div>
    <label>HAREKET ID</label>
    @Html.TextBoxFor(p => p.hareket_id, new { @class = "form-control" })
    <br />
    <label>KİTAP AD</label>

    @Html.TextBoxFor(p => p.TBLKITAP.kitap_ad, new { @class = "form-control" });
    <br />

    <label>UYE ADI</label>
    @Html.TextBoxFor(p => p.TBLUYELER.uye_ad, new { @class = "form-control" })
    <br />

    <label>PERSONEL</label>
    @Html.TextBoxFor(p => p.TBLPERSONEL.personel_bilgi, new { @class = "form-control" })
    <br />

    <label>ALIŞ TARİHİ</label>
    @Html.TextBoxFor(p => p.hareket_alistarih, new { @class = "form-control" })
    <br />

    <label>EN SON İADE TARİHİ</label>
    @Html.TextBoxFor(p => p.hareket_iadetarih, new { @class = "form-control" })
    <br />

    <label>KİTAP DURUMU</label>
    @Html.TextBoxFor(p => p.TBLKITAP.kitap_durum, new { @class = "form-control" })
    <br />


    <label style="padding:8px 14px 10px 8px">Üyenin getirdiği tarih</label>
    <input type="text" name="hareket_uyeningetirdigitarih" class="form-control" value="@DateTime.Now.ToShortDateString()" />
    <br />
    <button class="btn btn-warning">ÖDÜNÇ KİTABI İADE AL</button>
}