MvcKutuphaneProjesi/Controllers/UyeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using MvcKutuphaneProjesi.Models.Entity;
using PagedList;
using PagedList.Mvc;

namespace MvcKutuphaneProjesi.Controllers
{
    public class UyeController : Controller
    {
        // GET: Uye
        DBKUTUPHANEEntities db = new DBKUTUPHANEEntities();

        public ActionResult Index(int sayfa = 1)
        {
            var degerler = db.TBLUYELERs.ToList().ToPagedList(sayfa, 3);
            return View(degerler);
        }
        [HttpGet]
        public ActionResult UyeEkle()
        {
            return View();
        }
        [HttpPost]
        public ActionResult UyeEkle(TBLUYELER u)
        {
            db.TBLUYELERs.Add(u);
            db.SaveChanges();
            return View();
        }

        public ActionResult UyeSil(int id)
        {
            var silinecek_uye = db.TBLUYELERs.Find(id);
            db.TBLUYELERs.Remove(silinecek_uye);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult UyeGetir(int id)
        {
            var getirilecek_id = db.TBLUYELERs.Find(id);
            return View("UyeGetir", getirilecek_id);
        }


        public ActionResult UyeGuncelle(TBLUYELER p)
        {
            var uye = db.TBLUYELERs.Find(p.uye_id);
            uye.uye_ad = p.uye_ad;
            uye.uye_soyad = p.uye_soyad;
            uye.uye_mail = p.uye_mail;
            uye.uye_kullaniciadi = p.uye_kullaniciadi;
            uye.uye_sifre = p.uye_sifre;
            uye.uye_telofon = p.uye_telofon;


            db.SaveChanges();
            return RedirectToAction("Index");
        }
    }

}

MvcKutuphaneProjesi/Views/Uye/Index.cshtml
@using MvcKutuphaneProjesi.Models.Entity
@using PagedList
@using PagedList.Mvc
@model PagedList.IPagedList<TBLUYELER>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/Layout.cshtml";
}

<h2>Üyeler</h2>


<table class="table table-bordered">
    <thead>
        <tr>
            <th>UYE ID</th>
            <th>UYE ADI</th>
            <th>UYE SOYADI</th>
            <th>UYE MAIL</th>
            <th>UYE KULLANICI ADI</th>
            <th>UYE SIFRE</th>
            <th>UYE TELEFON</th>
            <th>SİL</th>
            <th>GÜNCELLE</th>
        </tr>
    </thead>

    @foreach (var uye in Model)
    {
        <tr>
            <td>@uye.uye_id</td>
            <td>@uye.uye_ad</td>
            <td>@uye.uye_soyad</td>
            <td>@uye.uye_mail</td>
            <td>@uye.uye_kullaniciadi</td>
            <td>@uye.uye_sifre</td>
            <td>@uye.uye_telofon</td>
            <td><a href="/Uye/UyeSil/@uye.uye_id/" class="btn btn-danger">SİL</a></td>
            <td><a href="/Uye/UyeGetir/@uye.uye_id/" class="btn btn-success">GÜNCELLE</a></td>
        </tr>
    }
</table>
@Html.PagedListPager((IPagedList)Model,sayfa=>Url.Action("Index",new { sayfa }))
<a href="/Uye/UyeEkle/" class="btn btn-primary">Yeni Uye Ekle</a>

MvcKutuphaneProjesi/Views/Uye/UyeEkle.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeEkle";
    Layout = "~/Views/Shared/Layout.cshtml";
}



<form class="form-group" method="post">
    <div>
    </div>
    <div style="margin-top:15px">
        <label>Üye Adı</label>
        <input type="text" class="form-control" name="uye_ad" />
    </div>
    <div style="margin-top:15px">
        <label>Üye Soyadı</label>
        <input type="text" class="form-control" name="uye_soyad" />
    </div>
    <div style="margin-top:15px">
        <label>Üye Mail</label>
        <input type="text" class="form-control" name="uye_mail" />
    </div>
    <div style="margin-top:15px">
        <label>Üye Kullanıcı Adı</label>
        <input type="text" class="form-control" name="uye_kullaniciadi" />
    </div>
    <div style="margin-top:15px">
        <label>Üye Şifre</label>
        <input type="text" class="form-control" name="uye_sifre" />
    </div>
    <div style="margin-top:15px">
        <label>Üye Telefon</label>
        <input type="text" class="form-control" name="uye_telofon" />
    </div>
    <br />  
    <button class="btn btn-warning" >Üye Ekle</button>
</form>

MvcKutuphaneProjesi/Views/Uye/UyeGetir.cshtml
@model MvcKutuphaneProjesi.Models.Entity.TBLUYELER
@{
    ViewBag.Title = "UyeGetir";
    Layout = "~/Views/Shared/Layout.cshtml";
}

@using (Html.BeginForm("UyeGuncelle", "Uye", FormMethod.Post))
{
    <div style="margin-top:15px"></div>
    <label style="margin-bottom:15px;margin-top:15px">Üye AD</label>
    @Html.TextBoxFor(u => u.uye_ad, new { @class = "form-control" })

    <label style="margin-top:15px">Üye SOYAD</label>
    @Html.TextBoxFor(u => u.uye_soyad, new { @class = "form-control" })

    <label style="margin-top:15px">Üye MAİL</label>
    @Html.TextBoxFor(u => u.uye_mail, new { @class = "form-control" })

    <label style="margin-top:15px"> Üye KULLANICI ADI</label>
    @Html.TextBoxFor(u => u.uye_kullaniciadi, new { @class = "form-control" })

    <label style="margin-top:15px"> Üye ŞİFRE</label>
    @Html.TextBoxFor(u => u.uye_sifre, new { @class = "form-control" })

    <label style="margin-top:15px"> Üye TELOFON</label>
    @Html.TextBoxFor(u => u.uye_telofon, new { @class = "form-control" })
    <br />
    <button class="btn btn-warning">Üye Bilgilerini Güncelle</button>
}